version: "3.1"
services:
    mysql:
        image: mysql:5.5
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=root
        ports:
            - 3306:3306
        volumes:
            - ../docker-data:/var/lib/mysql

    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginx_settings.conf:/etc/nginx/conf.d/nginx_settings.conf:ro

        restart: always
        privileged: true

    rampagecms:
        build: .
        depends_on:
            - mysql
        links:
            - mysql
        environment:
            - VIRTUAL_HOST=rampagecms
            - XDEBUG_CONFIG=remote_host=${EN0IP}
        volumes:
            - ../:/var/rampagecms
        restart: always

    composer:
        restart: 'no'
        image: composer/composer:2.2.10
        command: install --ignore-platform-reqs
        volumes:
            - ../:/app
